name: Supabase Keep Alive Auto

on:
  schedule:
    - cron: '0 12 */3 * *'
  workflow_dispatch:

jobs:
  ping_supabase_db:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Request to Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/profiles?limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
